import { course_images } from "./images";

const courses = [
  {
    id: "xMHCZl",
    category: "Kelas Lukis",
    image: course_images.kelaslukis1,
    course_name: "Sentuhan Kreatif",
    description:
      "Kesempurnaan di Setiap Goresan: Mengasah Keterampilan dan Memperluas Wawasan Seni Lukis melalui Kursus Kelas Seni yang Menantang, Memikat, dan Menghadirkan Keajaiban dalam Setiap Lukisan",
    rating_count: 3059,
    rating_star: 4.4,
    students: 18430,
    creator: "Avinash Jain, The Codex",
    updated_date: "9/2023",
    lang: "Indonesia",
    actual_price: 200.0,
    discounted_price: 50.0,
    what_you_will_learn: [
      "Setelah mengikuti kelas lukis, belajar banyak teknik dan keterampilan baru untuk menghasilkan karya seni yang lebih baik",
      "bisa mencampur warna dengan lebih baik dan menghasilkan efek-efek yang menarik dengan berbagai media",
      "belajar tentang komposisi yang baik dan cara memanfaatkan ruang kosong dalam gambar",
    ],
    content: [
      "Teknik Dasar Lukis",
      "Komposisi",
      "Perspektif",
      "Pemilihan Subjek",
      "Penggunaan Media",
      "Pewarnaan dan Bayangan",
      "Gaya dan Ekspresi",
    ],
  },
  {
    id: "dtfo9e",
    category: "Kelas Lukis",
    image: course_images.kelaslukis2,
    course_name: "Harmoni Warna",
    description:
      "Kesempurnaan di Setiap Goresan: Mengasah Keterampilan dan Memperluas Wawasan Seni Lukis melalui Kursus Kelas Seni yang Menantang, Memikat, dan Menghadirkan Keajaiban dalam Setiap Lukisan",
    rating_count: 3059,
    rating_star: 4.3,
    students: 184053,
    creator: "Jose Portilla",
    updated_date: "9/2019",
    lang: "english",
    actual_price: 200.0,
    discounted_price: 100.0,
    what_you_will_learn: [
      "Setelah mengikuti kelas lukis, belajar banyak teknik dan keterampilan baru untuk menghasilkan karya seni yang lebih baik",
      "bisa mencampur warna dengan lebih baik dan menghasilkan efek-efek yang menarik dengan berbagai media",
      "belajar tentang komposisi yang baik dan cara memanfaatkan ruang kosong dalam gambar",
    ],
    content: [
      "Teknik Dasar Lukis",
      "Komposisi",
      "Perspektif",
      "Pemilihan Subjek",
      "Penggunaan Media",
      "Pewarnaan dan Bayangan",
      "Gaya dan Ekspresi",
    ],
  },
  {
    id: "fLroW6",
    category: "Kelas Lukis",
    image: course_images.kelaslukis3,
    course_name: "Cahaya Kreativitas",
    description:
      "Kesempurnaan di Setiap Goresan: Mengasah Keterampilan dan Memperluas Wawasan Seni Lukis melalui Kursus Kelas Seni yang Menantang, Memikat, dan Menghadirkan Keajaiban dalam Setiap Lukisan",
    rating_count: 1844,
    rating_star: 4.3,
    students: 7330,
    creator: "Edwin Diaz, Coding Faculty Solutionss",
    updated_date: "5/2022",
    lang: "english",
    actual_price: 200.0,
    discounted_price: 50.0,
    what_you_will_learn: [
      "Setelah mengikuti kelas lukis, belajar banyak teknik dan keterampilan baru untuk menghasilkan karya seni yang lebih baik",
      "bisa mencampur warna dengan lebih baik dan menghasilkan efek-efek yang menarik dengan berbagai media",
      "belajar tentang komposisi yang baik dan cara memanfaatkan ruang kosong dalam gambar",
    ],
    content: [
      "Teknik Dasar Lukis",
      "Komposisi",
      "Perspektif",
      "Pemilihan Subjek",
      "Penggunaan Media",
      "Pewarnaan dan Bayangan",
      "Gaya dan Ekspresi",
    ],
  },
  {
    id: "VwkN_o",
    category: "Kelas Lukis",
    image: course_images.kelaslukis4,
    course_name: "Senandung Kuas",
    description:
      "Anda akan bergabung dengan sekelompok individu yang memiliki minat dan antusiasme yang sama terhadap seni gerakan ini. Anda akan diperkenalkan dengan berbagai teknik tari, gaya tari, dan jenis musik yang berbeda.",
    rating_count: 2780,
    rating_star: 4.3,
    students: 29082,
    creator: "Abrar Hussain",
    updated_date: "9/2019",
    lang: "english",
    actual_price: 200.0,
    discounted_price: 100.0,
    what_you_will_learn: [
      "Setelah mengikuti kelas lukis, belajar banyak teknik dan keterampilan baru untuk menghasilkan karya seni yang lebih baik",
      "bisa mencampur warna dengan lebih baik dan menghasilkan efek-efek yang menarik dengan berbagai media",
      "belajar tentang komposisi yang baik dan cara memanfaatkan ruang kosong dalam gambar",
    ],
    content: [
      "Teknik Dasar Lukis",
      "Komposisi",
      "Perspektif",
      "Pemilihan Subjek",
      "Penggunaan Media",
      "Pewarnaan dan Bayangan",
      "Gaya dan Ekspresi",
    ],
  },

  {
    id: "qjdYG4",
    category: "kelas tari",
    image: course_images.kelastari1,
    course_name: "Rhythm & Moves",
    description:
      "Anda akan melakukan serangkaian latihan fisik untuk mempersiapkan tubuh Anda untuk gerakan-gerakan yang akan datang. Pemanasan ini bertujuan untuk meningkatkan fleksibilitas, kekuatan, dan kelincahan tubuh Anda.",
    rating_count: 2760,
    rating_star: 4.1,
    students: 33455,
    creator: "Tech Learning Network, Mark Lassoff",
    updated_date: "11/2020",
    lang: "english",
    actual_price: 200.0,
    discounted_price: 50.0,
    what_you_will_learn: [
      "Teknik Gerakan: Anda akan belajar teknik dasar gerakan dalam gaya tari yang dipelajari. Ini meliputi pengembangan kekuatan, fleksibilitas, keseimbangan, dan kelincahan tubuh Anda.",
      "Koreografi: Mengikuti kelas tari memberi Anda kesempatan untuk belajar dan melatih koreografi. Anda akan mempelajari berbagai urutan gerakan yang digabungkan menjadi tarian lengkap.",
      "Pemahaman Musik: Dalam kelas tari, Anda akan belajar menghubungkan gerakan dengan musik. Anda akan mempelajari cara mendengarkan dan merespons ritme, melodi, dan struktur musik untuk menginterpretasikan gerakan dengan tepat.",
    ],
    content: [
      "Pemanasan dan Teknik Fisik",
      "Teknik Dasar",
      "Koreografi dan Urutan Gerakan",
      "Ekspresi dan Interpretasi",
      "Perbaikan Teknik dan Kinerja",
      "Pengetahuan Musikal",
      "Pertunjukan dan Pementasan:",
    ],
  },
  {
    id: "3pm9Ab",
    category: "kelas tari",
    image: course_images.kelastari2,
    course_name: "Dance Fusion",
    description:
      "Anda akan diajak untuk berlatih koreografi yang diajarkan instruktur. Koreografi ini biasanya terdiri dari serangkaian gerakan yang disusun dalam sebuah tarian lengkap. ",
    rating_count: 6200,
    rating_star: 4.3,
    students: 90360,
    creator: "Kalob Taulien",
    updated_date: "9/2019",
    lang: "english",
    actual_price: 200.0,
    discounted_price: 100.0,
    what_you_will_learn: [
      "Teknik Gerakan: Anda akan belajar teknik dasar gerakan dalam gaya tari yang dipelajari. Ini meliputi pengembangan kekuatan, fleksibilitas, keseimbangan, dan kelincahan tubuh Anda.",
      "Koreografi: Mengikuti kelas tari memberi Anda kesempatan untuk belajar dan melatih koreografi. Anda akan mempelajari berbagai urutan gerakan yang digabungkan menjadi tarian lengkap.",
      "Pemahaman Musik: Dalam kelas tari, Anda akan belajar menghubungkan gerakan dengan musik. Anda akan mempelajari cara mendengarkan dan merespons ritme, melodi, dan struktur musik untuk menginterpretasikan gerakan dengan tepat.",
    ],
    content: [
      "Pemanasan dan Teknik Fisik",
      "Teknik Dasar",
      "Koreografi dan Urutan Gerakan",
      "Ekspresi dan Interpretasi",
      "Perbaikan Teknik dan Kinerja",
      "Pengetahuan Musikal",
      "Pertunjukan dan Pementasan:",
    ],
  },
  {
    id: "RuUs0x",
    category: "kelas musik",
    image: course_images.kelasmusik1,
    course_name: "Musikalitas Fundamental",
    description:
      "Selama kelas musik, siswa akan belajar tentang melodi, ritme, harmoni, dan dinamika. Mereka akan mempelajari bagaimana membaca not musik, memainkan lagu dengan benar, dan mengembangkan keterampilan improvisasi. Siswa juga akan diajarkan tentang sejarah musik dan mempelajari tentang komponis dan genre musik yang berbeda.",
    rating_count: 1740,
    rating_star: 4,
    students: 22309,
    creator: "Tech Learning Network, Mark Lassoff",
    updated_date: "10/2020",
    lang: "english",
    actual_price: 200.0,
    discounted_price: 50.0,
    what_you_will_learn: [
      "Teori musik: Anda akan mempelajari prinsip-prinsip dasar musik, seperti membaca notasi musik, memahami ritme, harmoni, dan struktur musik.",
      "Teknik instrumen: Jika Anda memilih untuk mempelajari instrumen tertentu, Anda akan mengembangkan keterampilan teknis dalam memainkan instrumen tersebut.",
      "Komposisi: Anda akan mempelajari cara menggubah musik sendiri, termasuk mengatur melodi, harmoni, dan ritme menjadi lagu atau karya musik yang utuh.",
      "Memainkan musik secara ensemble: Anda akan belajar bermain musik secara kolaboratif dengan orang lain dalam kelompok seperti band atau orke",
    ],
    content: [
      "Teori musik: Ini termasuk pembelajaran tentang notasi musik, membaca partitur, memahami ritme",
      "Teknik instrumen: Jika Anda memilih untuk mempelajari instrumen tertentu, Anda akan belajar tentang teknik dasar dan maju dalam memainkan instrumen tersebut. ",
      "Pendengaran dan analisis musik: Anda akan melatih pendengaran musik Anda untuk mengenali elemen-elemen dalam musik seperti nada, interval, akord, dan gaya komposisi.",
      "Komposisi dan improvisasi: Anda akan belajar tentang komposisi musik, yaitu membuat musik sendiri dengan menggubah melodi, harmoni, dan ritme. ",
      "Pentas Seni / Pensi",
    ],
  },
  {
    id: "e_0hBc",
    category: "kelas musik",
    image: course_images.kelasmusik2,
    course_name: "Harmoni dan Teori Musik",
    description:
      "Selama kelas musik, siswa akan belajar tentang melodi, ritme, harmoni, dan dinamika. Mereka akan mempelajari bagaimana membaca not musik, memainkan lagu dengan benar, dan mengembangkan keterampilan improvisasi. Siswa juga akan diajarkan tentang sejarah musik dan mempelajari tentang komponis dan genre musik yang berbeda.",
    rating_count: 1577,
    rating_star: 4.8,
    students: 33100,
    creator: "Evan Kimbrell",
    updated_date: "8/2022",
    lang: "english",
    actual_price: 200.0,
    discounted_price: 100.0,
    what_you_will_learn: [
      "Teori musik: Anda akan mempelajari prinsip-prinsip dasar musik, seperti membaca notasi musik, memahami ritme, harmoni, dan struktur musik.",
      "Teknik instrumen: Jika Anda memilih untuk mempelajari instrumen tertentu, Anda akan mengembangkan keterampilan teknis dalam memainkan instrumen tersebut.",
      "Komposisi: Anda akan mempelajari cara menggubah musik sendiri, termasuk mengatur melodi, harmoni, dan ritme menjadi lagu atau karya musik yang utuh.",
      "Memainkan musik secara ensemble: Anda akan belajar bermain musik secara kolaboratif dengan orang lain dalam kelompok seperti band atau orke",
    ],
    content: [
      "Teori musik: Ini termasuk pembelajaran tentang notasi musik, membaca partitur, memahami ritme",
      "Teknik instrumen: Jika Anda memilih untuk mempelajari instrumen tertentu, Anda akan belajar tentang teknik dasar dan maju dalam memainkan instrumen tersebut. ",
      "Pendengaran dan analisis musik: Anda akan melatih pendengaran musik Anda untuk mengenali elemen-elemen dalam musik seperti nada, interval, akord, dan gaya komposisi.",
      "Komposisi dan improvisasi: Anda akan belajar tentang komposisi musik, yaitu membuat musik sendiri dengan menggubah melodi, harmoni, dan ritme. ",
      "Pentas Seni / Pensi",
    ],
  },
  {
    id: "z9dxdw",
    category: "kelas musik",
    image: course_images.kelasmusik3,
    course_name: "Pengantar Musik Klasik",
    description:
      "Selama kelas musik, siswa akan belajar tentang melodi, ritme, harmoni, dan dinamika. Mereka akan mempelajari bagaimana membaca not musik, memainkan lagu dengan benar, dan mengembangkan keterampilan improvisasi. Siswa juga akan diajarkan tentang sejarah musik dan mempelajari tentang komponis dan genre musik yang berbeda.",
    rating_count: 2941,
    rating_star: 4.6,
    students: 10450,
    creator: "Brad Hussey",
    updated_date: "3/2022",
    lang: "english",
    actual_price: 200.0,
    discounted_price: 100.0,
    what_you_will_learn: [
      "Teori musik: Anda akan mempelajari prinsip-prinsip dasar musik, seperti membaca notasi musik, memahami ritme, harmoni, dan struktur musik.",
      "Teknik instrumen: Jika Anda memilih untuk mempelajari instrumen tertentu, Anda akan mengembangkan keterampilan teknis dalam memainkan instrumen tersebut.",
      "Komposisi: Anda akan mempelajari cara menggubah musik sendiri, termasuk mengatur melodi, harmoni, dan ritme menjadi lagu atau karya musik yang utuh.",
      "Memainkan musik secara ensemble: Anda akan belajar bermain musik secara kolaboratif dengan orang lain dalam kelompok seperti band atau orke",
    ],
    content: [
      "Teori musik: Ini termasuk pembelajaran tentang notasi musik, membaca partitur, memahami ritme",
      "Teknik instrumen: Jika Anda memilih untuk mempelajari instrumen tertentu, Anda akan belajar tentang teknik dasar dan maju dalam memainkan instrumen tersebut. ",
      "Pendengaran dan analisis musik: Anda akan melatih pendengaran musik Anda untuk mengenali elemen-elemen dalam musik seperti nada, interval, akord, dan gaya komposisi.",
      "Komposisi dan improvisasi: Anda akan belajar tentang komposisi musik, yaitu membuat musik sendiri dengan menggubah melodi, harmoni, dan ritme. ",
      "Pentas Seni / Pensi",
    ],
  },
  {
    id: "X8Pg1X",
    category: "kelas tari",
    image: course_images.kelastari3,
    course_name: "Expressive Beats",
    description:
      "mengikuti kelas tari juga memberikan kesempatan untuk berinteraksi dengan sesama peserta. Anda dapat belajar secara kolektif, saling berbagi pengetahuan dan pengalaman, serta memberikan dukungan dan inspirasi satu sama lain.",
    rating_count: 32103,
    rating_star: 4.5,
    students: 204985,
    creator: "Kirill Eremenko, Ligency Team",
    updated_date: "9/2022",
    lang: "english",
    actual_price: 200.0,
    discounted_price: 100.0,
    what_you_will_learn: [
      "Teknik Gerakan: Anda akan belajar teknik dasar gerakan dalam gaya tari yang dipelajari. Ini meliputi pengembangan kekuatan, fleksibilitas, keseimbangan, dan kelincahan tubuh Anda.",
      "Koreografi: Mengikuti kelas tari memberi Anda kesempatan untuk belajar dan melatih koreografi. Anda akan mempelajari berbagai urutan gerakan yang digabungkan menjadi tarian lengkap.",
      "Pemahaman Musik: Dalam kelas tari, Anda akan belajar menghubungkan gerakan dengan musik. Anda akan mempelajari cara mendengarkan dan merespons ritme, melodi, dan struktur musik untuk menginterpretasikan gerakan dengan tepat.",
    ],
    content: [
      "What is Data Science?",
      "Part 1: Visualisation",
      "Introduction to Tableau",
      "Advanced Data Mining with Tableau",
      "Stats Refresher",
      "Simple Linear Regression",
      "Model maintenance",
      "SQL Programming for Data Science",
    ],
  },
  {
    id: "9Ui0L1",
    category: "kelas tari",
    image: course_images.kelastari4,
    course_name: "Creative Choreography",
    description:
      "Mengikuti kelas tari bukan hanya tentang meningkatkan keterampilan tari Anda, tetapi juga tentang kebugaran fisik dan kesehatan mental. Aktivitas fisik yang terlibat dalam tarian membantu meningkatkan kekuatan, kelenturan, dan kardiovaskular. ",
    rating_count: 27687,
    rating_star: 4.5,
    students: 166929,
    creator: "Sundog Education by Frank Kane",
    updated_date: "2/2022",
    lang: ["english", "french"],
    actual_price: 200.0,
    discounted_price: 50.0,
    what_you_will_learn: [
      "Teknik Gerakan: Anda akan belajar teknik dasar gerakan dalam gaya tari yang dipelajari. Ini meliputi pengembangan kekuatan, fleksibilitas, keseimbangan, dan kelincahan tubuh Anda.",
      "Koreografi: Mengikuti kelas tari memberi Anda kesempatan untuk belajar dan melatih koreografi. Anda akan mempelajari berbagai urutan gerakan yang digabungkan menjadi tarian lengkap.",
      "Pemahaman Musik: Dalam kelas tari, Anda akan belajar menghubungkan gerakan dengan musik. Anda akan mempelajari cara mendengarkan dan merespons ritme, melodi, dan struktur musik untuk menginterpretasikan gerakan dengan tepat.",
    ],
    content: [
      "Pemanasan dan Teknik Fisik",
      "Teknik Dasar",
      "Koreografi dan Urutan Gerakan",
      "Ekspresi dan Interpretasi",
      "Perbaikan Teknik dan Kinerja",
      "Pengetahuan Musikal",
      "Pertunjukan dan Pementasan:",
    ],
  },
  {
    id: "TKGumi",
    category: "data science",
    image: course_images.data_science_3,
    course_name: "Data Science: Deep Learning and Neural Networks in Python",
    description:
      "Kesempurnaan di Setiap Goresan: Mengasah Keterampilan dan Memperluas Wawasan Seni Lukis melalui Kursus Kelas Seni yang Menantang, Memikat, dan Menghadirkan Keajaiban dalam Setiap Lukisan",
    rating_count: 8513,
    rating_star: 4.8,
    students: 50184,
    creator: "Lazy Programmer Inc.",
    updated_date: "8/2022",
    lang: ["english", "Portuguese"],
    actual_price: 200.0,
    discounted_price: 100.0,
    what_you_will_learn: [
      "Teknik Gerakan: Anda akan belajar teknik dasar gerakan dalam gaya tari yang dipelajari. Ini meliputi pengembangan kekuatan, fleksibilitas, keseimbangan, dan kelincahan tubuh Anda.",
      "Koreografi: Mengikuti kelas tari memberi Anda kesempatan untuk belajar dan melatih koreografi. Anda akan mempelajari berbagai urutan gerakan yang digabungkan menjadi tarian lengkap.",
      "Pemahaman Musik: Dalam kelas tari, Anda akan belajar menghubungkan gerakan dengan musik. Anda akan mempelajari cara mendengarkan dan merespons ritme, melodi, dan struktur musik untuk menginterpretasikan gerakan dengan tepat.",
    ],
    content: [
      "Pemanasan dan Teknik Fisik",
      "Teknik Dasar",
      "Koreografi dan Urutan Gerakan",
      "Ekspresi dan Interpretasi",
      "Perbaikan Teknik dan Kinerja",
      "Pengetahuan Musikal",
      "Pertunjukan dan Pementasan:",
    ],
  },
];

export default courses;
